version: "3.9"

services:
  api:
    build: .
    container_name: test_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: ["sh", "-c", "./wait-for.sh http://qdrant:6333/collections -- ./run.sh"]
    networks:
      - sharing_net

  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: test_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - sharing_net

volumes:
  qdrant_data:

networks:
  sharing_net:
